openapi: 3.0.2
info:
  title: ion-storage
  version: '${project.version}'
  description: ion storage abstraction service
  contact:
    name: 'Connexta, LLC'
    url: 'https://connexta.com'
  license:
    name: GNU Lesser General Public License
    url: 'http://www.gnu.org/licenses/lgpl.html'
servers:
- url: '${rest.server.url}'

paths:

  /folder:
    summary: root dir
    get:
      summary: 'Retrieve metadata'
      operationId: getStorageRoot

  /folder/{folderName}:
    get:
      summary: Fetches file
      parameters:
      - in: path
        name: path
        schema:
          type: string
        required: true
        description: Write something here, please
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    post:
      summary: Add file to path
      parameters:
      - in: path
        name: path
        schema:
          type: string
        required: true
        description: Write something here, please
      description: >-
        uploads given file and places it in the given path, if the path doesn't
        exist it will be created.
      operationId: postStorageRoot
      responses:
        default:
          description: Write something here, please

    put:
      summary: Modify file at path
      parameters:
      - in: path
        name: path
        schema:
          type: string
        required: true
        description: Write something here, please
      description: >-
        uploads given file and places it in the given path, if the path doesn't
        exist it will be created.
      operationId: putStorageRoot
      responses:
        default:
          description: Default error sample response

    delete:
      summary: Delete file at path
      parameters:
      - in: path
        name: path
        schema:
          type: string
        required: true
        description: Write something here, please
      description: >-
        uploads given file and places it in the given path, if the path doesn't
        exist it will be created.
      operationId: deleteStorageRoot
      responses:
        default:
          description: Default error sample response

